# Generated by Django 5.2.14 on 2026-05-15 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_city_company_complement_company_legal_name_and_more'),
        ('researchers', '0004_alter_researcher_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingHistory',
            fields=[
                ('id_history', models.AutoField(db_column='id_historico', primary_key=True, serialize=False)),
                ('search_query', models.TextField(db_column='query_busca', help_text='Texto enviado para busca inteligente')),
                ('query_type', models.CharField(choices=[('find_companies', 'Encontrar Empresas'), ('find_researchers', 'Encontrar Pesquisadores')], db_column='tipo_query', max_length=20)),
                ('results_count', models.IntegerField(db_column='quantidade_resultados', default=0)),
                ('ai_response', models.JSONField(db_column='resposta_ia', help_text='Resposta completa da IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='matching_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Matching',
                'verbose_name_plural': 'Históricos de Matching',
                'db_table': 'historico_matching',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingProfile',
            fields=[
                ('id_profile', models.AutoField(db_column='id_perfil', primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('researcher', 'Pesquisador'), ('company', 'Empresa')], db_column='tipo_perfil', max_length=20)),
                ('description', models.TextField(db_column='descricao', help_text='Descrição das competências, necessidades ou expectativas')),
                ('keywords', models.TextField(db_column='palavras_chave', help_text='Palavras-chave separadas por vírgula')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='data_atualizacao')),
                ('is_active', models.BooleanField(db_column='ativo', default=True)),
                ('company', models.OneToOneField(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile_company', to='companies.company')),
                ('researcher', models.OneToOneField(blank=True, db_column='id_pesquisador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile_researcher', to='researchers.researcher')),
                ('user', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='matching_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Matching',
                'verbose_name_plural': 'Perfis de Matching',
                'db_table': 'perfil_matching',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id_match', models.AutoField(db_column='id_matching', primary_key=True, serialize=False)),
                ('compatibility_score', models.FloatField(db_column='score_compatibilidade', help_text='Score de 0 a 100')),
                ('match_reason', models.TextField(db_column='motivo_matching', help_text='Explicação do matching gerada pela IA')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado'), ('contacted', 'Contatado'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], db_column='status', default='pending', max_length=20)),
                ('search_query', models.TextField(blank=True, db_column='query_busca', help_text='Query original que gerou este match', null=True)),
                ('ai_analysis', models.JSONField(blank=True, db_column='analise_ia', help_text='Análise detalhada da IA em formato JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='data_criacao')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='data_atualizacao')),
                ('company', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_company', to='companies.company')),
                ('researcher', models.ForeignKey(db_column='id_pesquisador', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_researcher', to='researchers.researcher')),
            ],
            options={
                'verbose_name': 'Matching',
                'verbose_name_plural': 'Matchings',
                'db_table': 'matching',
                'indexes': [models.Index(fields=['compatibility_score'], name='matching_score_c_3b2a73_idx'), models.Index(fields=['status'], name='matching_status_824414_idx'), models.Index(fields=['created_at'], name='matching_data_cr_786600_idx')],
                'unique_together': {('researcher', 'company')},
            },
        ),
    ]
