# Generated by Django 6.0.4 on 2026-04-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('registration_status', models.CharField(blank=True, db_column='situacao_cadastral', max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
