# Generated by Django 6.0.4 on 2026-04-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, db_column='municipio', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='complement',
            field=models.CharField(blank=True, db_column='complemento', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, db_column='razao_social', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='neighborhood',
            field=models.CharField(blank=True, db_column='bairro', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.CharField(blank=True, db_column='numero', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, db_column='uf', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, db_column='logradouro', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, db_column='cep', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, db_column='nome', max_length=200, null=True),
        ),
    ]
