# Generated by Django 6.0.4 on 2026-04-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id_education', models.AutoField(db_column='id_formacao', primary_key=True, serialize=False)),
                ('course', models.CharField(db_column='curso', max_length=200)),
                ('institution', models.CharField(db_column='instituicao', max_length=200)),
                ('start_date', models.DateField(db_column='dt_inicio')),
                ('end_date', models.DateField(db_column='dt_termino')),
                ('resume', models.ForeignKey(db_column='id_curriculo', on_delete=django.db.models.deletion.PROTECT, related_name='education', to='resumes.resume')),
            ],
            options={
                'db_table': 'formacao',
            },
        ),
    ]
