# Generated by Django 6.0.4 on 2026-04-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id_university', models.AutoField(db_column='id_universidade', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=255)),
            ],
            options={
                'db_table': 'universidade',
            },
        ),
    ]
