# Generated by Django 5.2.13 on 2026-05-13

import django.db.models.deletion
import pgvector.django
import pgvector.django.indexes
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_alter_research_researcher'),
        ('researchers', '0004_alter_researcher_resume'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;',
        ),
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS unaccent;',
            reverse_sql='DROP EXTENSION IF EXISTS unaccent;',
        ),
        migrations.CreateModel(
            name='SearchResearchIndex',
            fields=[
                ('search_text', models.TextField(blank=True, default='')),
                ('search_tsv', SearchVectorField(null=True)),
                ('embedding', pgvector.django.VectorField(dimensions=256, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'research',
                    models.OneToOneField(
                        db_column='id_pesquisa',
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='search_index',
                        serialize=False,
                        to='research.research',
                    ),
                ),
            ],
            options={
                'db_table': 'search_pesquisa',
            },
        ),
        migrations.CreateModel(
            name='SearchResearcherIndex',
            fields=[
                ('search_text', models.TextField(blank=True, default='')),
                ('search_tsv', SearchVectorField(null=True)),
                ('embedding', pgvector.django.VectorField(dimensions=256, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'researcher',
                    models.OneToOneField(
                        db_column='id_pesquisador',
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='search_index',
                        serialize=False,
                        to='researchers.researcher',
                    ),
                ),
            ],
            options={
                'db_table': 'search_pesquisador',
            },
        ),
        migrations.AddIndex(
            model_name='searchresearchindex',
            index=GinIndex(fields=['search_tsv'], name='idx_search_pesquisa_tsv'),
        ),
        migrations.AddIndex(
            model_name='searchresearchindex',
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=['embedding'],
                m=16,
                name='idx_search_pesquisa_vec',
                opclasses=['vector_cosine_ops'],
            ),
        ),
        migrations.AddIndex(
            model_name='searchresearcherindex',
            index=GinIndex(fields=['search_tsv'], name='idx_search_pesq_tsv'),
        ),
        migrations.AddIndex(
            model_name='searchresearcherindex',
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=['embedding'],
                m=16,
                name='idx_search_pesq_vec',
                opclasses=['vector_cosine_ops'],
            ),
        ),
    ]
