# Generated by Django 6.0.4 on 2026-05-13

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresearchindex',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='searchresearcherindex',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384, null=True),
        ),
    ]
