# Generated by Django 6.0.4 on 2026-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=255)),
            ],
            options={
                'db_table': 'area_pesquisa',
            },
        ),
    ]
