# Generated by Django 6.0.4 on 2026-04-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id_resume', models.AutoField(db_column='id_curriculo', primary_key=True, serialize=False)),
                ('skill', models.ManyToManyField(related_name='resume', to='skills.skill')),
            ],
            options={
                'db_table': 'curriculo',
            },
        ),
    ]
