# Generated by Django 6.0.4 on 2026-04-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id_experience', models.AutoField(db_column='id_experiencia', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='descricao')),
                ('start_date', models.DateField(db_column='dt_inicio')),
                ('end_date', models.DateField(blank=True, db_column='dt_termino', null=True)),
                ('resume', models.ForeignKey(db_column='id_curriculo', on_delete=django.db.models.deletion.PROTECT, related_name='experience', to='resumes.resume')),
            ],
            options={
                'db_table': 'experiencia',
            },
        ),
    ]
