# Generated by Django 6.0.4 on 2026-04-21

from django.db import migrations, models

import apps.users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(db_column='senha', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('id_user', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_type', models.PositiveSmallIntegerField(choices=[(1, 'pesquisador'), (2, 'empresa')], db_column='id_tipo', default=1)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='dt_atualizacao')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
