# Generated by Django 6.0.4 on 2026-04-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_alter_research_researcher'),
        ('researchers', '0004_alter_researcher_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCandidate',
            fields=[
                ('id_candidate', models.AutoField(db_column='id_candidato', primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('ai', 'ai'), ('interest', 'interest'), ('manual', 'manual')], default='manual', max_length=20)),
                ('score_match', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('suggested', 'suggested'), ('interested', 'interested'), ('under_review', 'under_review'), ('approved', 'approved'), ('rejected', 'rejected')], default='suggested', max_length=20)),
                ('interest_message', models.TextField(blank=True, null=True)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_atualizacao')),
                ('research', models.ForeignKey(db_column='id_pesquisa', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='research.research')),
                ('researcher', models.ForeignKey(db_column='id_pesquisador', on_delete=django.db.models.deletion.CASCADE, related_name='research_candidates', to='researchers.researcher')),
            ],
            options={
                'db_table': 'pesquisa_candidato',
                'indexes': [models.Index(fields=['research', 'status'], name='idx_candidate_status'), models.Index(fields=['research', 'source'], name='idx_candidate_source'), models.Index(fields=['research', '-score_match'], name='idx_candidate_score')],
                'constraints': [models.UniqueConstraint(fields=('research', 'researcher'), name='uq_pesquisa_candidato_pesquisa_pesquisador')],
            },
        ),
    ]
