# Generated by Django 6.0.4 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcandidate',
            name='match_reasons',
            field=models.JSONField(blank=True, db_column='motivos_match', null=True),
        ),
        migrations.AddField(
            model_name='researchcandidate',
            name='score_features',
            field=models.JSONField(blank=True, db_column='features_score', null=True),
        ),
    ]
