# Generated by Django 5.2.14 on 2026-06-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_candidates', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchcandidate',
            name='match_reasons',
            field=models.JSONField(blank=True, db_column='motivos_match', null=True),
        ),
        migrations.AddField(
            model_name='researchcandidate',
            name='score_features',
            field=models.JSONField(blank=True, db_column='features_score', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('proposta_recebida', 'Proposta Recebida'), ('status_alterado', 'Status Alterado'), ('match_automatico', 'Match Automático'), ('deadline_proximo', 'Deadline Próximo'), ('novo_match_disponivel', 'Novo Match Disponível'), ('feedback_recebido', 'Feedback Recebido'), ('pesquisa_atualizada', 'Pesquisa Atualizada'), ('pesquisa_encerrada', 'Pesquisa Encerrada')], max_length=30),
        ),
    ]
