# Generated by Django 6.0.4 on 2026-04-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id_researcher', models.AutoField(db_column='id_pesquisador', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nome', max_length=200)),
                ('availability', models.BooleanField(blank=True, db_column='disponibilidade', null=True)),
                ('status', models.BooleanField(default=True)),
                ('resume', models.OneToOneField(db_column='id_curriculo', on_delete=django.db.models.deletion.PROTECT, related_name='researcher', to='resumes.resume')),
                ('university', models.ForeignKey(db_column='id_universidade', on_delete=django.db.models.deletion.PROTECT, related_name='researcher', to='universities.university')),
            ],
            options={
                'db_table': 'pesquisador',
            },
        ),
    ]
