# Generated by Django 6.0.4 on 2026-04-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_area', '0001_initial'),
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='area',
            field=models.ManyToManyField(related_name='researcher', to='research_area.researcharea'),
        ),
    ]
