# Generated by Django 6.0.4 on 2026-04-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_researcher_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='user',
            field=models.OneToOneField(
                blank=True,
                db_column='id_usuario',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='researcher_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
