# Generated by Django 6.0.4 on 2026-04-25 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0003_researcher_user'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='resume',
            field=models.OneToOneField(blank=True, db_column='id_curriculo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='researcher', to='resumes.resume'),
        ),
    ]
