# Generated by Django 6.0.4 on 2026-04-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id_skill', models.AutoField(db_column='id_habilidade', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='descricao', max_length=255)),
            ],
            options={
                'db_table': 'habilidade',
            },
        ),
    ]
