# Generated by Django 6.0.4 on 2026-04-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('research_area', '0001_initial'),
        ('researchers', '0002_researcher_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id_research', models.AutoField(db_column='id_pesquisa', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='titulo', max_length=200)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('scope', models.TextField(db_column='escopo')),
                ('goal', models.TextField(db_column='objetivo')),
                ('justification', models.TextField(db_column='justificativa')),
                ('results', models.TextField(db_column='resultados')),
                ('deadline', models.DateTimeField(db_column='prazo')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='dt_atualizacao')),
                ('area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, related_name='research', to='research_area.researcharea')),
                ('company', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='research', to='companies.company')),
                ('researcher', models.ForeignKey(db_column='id_universidade', on_delete=django.db.models.deletion.PROTECT, related_name='research', to='researchers.researcher')),
            ],
            options={
                'db_table': 'pesquisa',
            },
        ),
    ]
