# Generated by Django 6.0.4 on 2026-04-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('researchers', '0004_alter_researcher_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='researcher',
            field=models.ForeignKey(blank=True, db_column='id_universidade', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research', to='researchers.researcher'),
        ),
    ]
