# Generated by Django 6.0.4 on 2026-05-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_research_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(default='aberta', max_length=20),
        ),
    ]
