# Generated by Django 5.2.14 on 2026-06-04 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(db_column='id_notificacao', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='tipo', max_length=50)),
                ('title', models.CharField(db_column='titulo', max_length=255)),
                ('message', models.TextField(db_column='mensagem')),
                ('is_read', models.BooleanField(db_column='lida', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_criacao')),
                ('related_id', models.IntegerField(blank=True, db_column='id_relacionado', null=True)),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacao',
                'ordering': ['-created_at'],
            },
        ),
    ]
